-- ============================================================================
-- Data Quality Pipeline
-- Gold Analytics Layer
-- File: 16_gold_analytics.sql
--
-- Purpose:
--   Build, validate, export and verify the five Gold analytical datasets.
--
-- Common business rules:
--   - Gold consumes validated Silver tables only.
--   - Revenue analysis considers completed orders.
--   - Product-based profitability analysis considers active products.
--   - Net revenue:
--       quantity * unit_price * (1 - discount / 100)
--   - Total margin:
--       quantity * (effective_selling_price - unit_cost)
--   - Monetary metrics are rounded to 2 decimal places.
-- ============================================================================


-- ============================================================================
-- 01. GOLD COMPLETED ORDER REVENUE
-- Business question:
-- How much net revenue was generated by each completed order?
--
-- Grain: one row per completed order
-- ============================================================================

CREATE OR REPLACE TABLE gold_completed_order_revenue AS
SELECT
    oc.order_no,
    oc.order_date,
    ROUND(
        SUM(
            oic.quantity
            * oic.unit_price
            * (1 - oic.discount / 100)
        ),
        2
    ) AS net_revenue
FROM orders_clean AS oc
INNER JOIN order_items_clean AS oic
    ON oc.order_no = oic.order_no
WHERE oc.status = 'completed'
GROUP BY
    oc.order_no,
    oc.order_date;


-- Validation

SELECT *
FROM gold_completed_order_revenue
ORDER BY net_revenue DESC;

SELECT COUNT(*) AS row_count
FROM gold_completed_order_revenue;

SELECT COUNT(DISTINCT order_no) AS distinct_orders
FROM gold_completed_order_revenue;

SELECT
    order_no,
    COUNT(*) AS occurrences
FROM gold_completed_order_revenue
GROUP BY order_no
HAVING COUNT(*) > 1;


-- Export

COPY gold_completed_order_revenue
TO '/mnt/c/Users/Lenovo/DataProjects/data-quality-pipeline/data/04-gold/gold_completed_order_revenue.parquet'
(FORMAT PARQUET);


-- Read-back verification

SELECT *
FROM read_parquet(
    '/mnt/c/Users/Lenovo/DataProjects/data-quality-pipeline/data/04-gold/gold_completed_order_revenue.parquet'
);


-- ============================================================================
-- 02. GOLD PRODUCT PERFORMANCE
-- Business question:
-- Which products generate the most net revenue, units sold and margin?
--
-- Grain: one row per active product with completed-order activity
-- ============================================================================

CREATE OR REPLACE TABLE gold_product_performance AS
SELECT
    pc.prod_code,
    pc.product_name,

    SUM(oic.quantity) AS units_sold,

    ROUND(
        SUM(
            oic.quantity
            * oic.unit_price
            * (1 - oic.discount / 100)
        ),
        2
    ) AS net_revenue,

    ROUND(
        SUM(
            oic.quantity
            * (
                oic.unit_price * (1 - oic.discount / 100)
                - pc.unit_cost
            )
        ),
        2
    ) AS total_margin,

    ROUND(
        SUM(
            oic.quantity
            * (
                oic.unit_price * (1 - oic.discount / 100)
                - pc.unit_cost
            )
        ) / SUM(oic.quantity),
        2
    ) AS margin_per_unit

FROM products_clean AS pc
INNER JOIN order_items_clean AS oic
    ON pc.prod_code = oic.product_code
INNER JOIN orders_clean AS oc
    ON oic.order_no = oc.order_no
WHERE pc.active = 'Y'
  AND oc.status = 'completed'
GROUP BY
    pc.prod_code,
    pc.product_name;


-- Validation

SELECT *
FROM gold_product_performance
ORDER BY margin_per_unit DESC;

SELECT COUNT(*) AS row_count
FROM gold_product_performance;

SELECT COUNT(DISTINCT prod_code) AS distinct_products
FROM gold_product_performance;

SELECT
    prod_code,
    COUNT(*) AS occurrences
FROM gold_product_performance
GROUP BY prod_code
HAVING COUNT(*) > 1;


-- Export

COPY gold_product_performance
TO '/mnt/c/Users/Lenovo/DataProjects/data-quality-pipeline/data/04-gold/gold_product_performance.parquet'
(FORMAT PARQUET);


-- Read-back verification

SELECT *
FROM read_parquet(
    '/mnt/c/Users/Lenovo/DataProjects/data-quality-pipeline/data/04-gold/gold_product_performance.parquet'
);


-- ============================================================================
-- 03. GOLD CATEGORY PERFORMANCE
-- Business question:
-- Which product categories generate the most net revenue and margin?
--
-- Grain: one row per product category
-- ============================================================================

CREATE OR REPLACE TABLE gold_category_performance AS
SELECT
    pc.category,

    SUM(oic.quantity) AS units_sold,

    ROUND(
        SUM(
            oic.quantity
            * oic.unit_price
            * (1 - oic.discount / 100)
        ),
        2
    ) AS net_revenue,

    ROUND(
        SUM(
            oic.quantity
            * (
                oic.unit_price * (1 - oic.discount / 100)
                - pc.unit_cost
            )
        ),
        2
    ) AS total_margin,

    ROUND(
        SUM(
            oic.quantity
            * (
                oic.unit_price * (1 - oic.discount / 100)
                - pc.unit_cost
            )
        ) / SUM(oic.quantity),
        2
    ) AS margin_per_unit

FROM products_clean AS pc
INNER JOIN order_items_clean AS oic
    ON pc.prod_code = oic.product_code
INNER JOIN orders_clean AS oc
    ON oic.order_no = oc.order_no
WHERE oc.status = 'completed'
  AND pc.active = 'Y'
GROUP BY pc.category;


-- Validation

SELECT *
FROM gold_category_performance
ORDER BY total_margin DESC;

SELECT COUNT(*) AS row_count
FROM gold_category_performance;

SELECT COUNT(DISTINCT category) AS distinct_categories
FROM gold_category_performance;

SELECT
    category,
    COUNT(*) AS occurrences
FROM gold_category_performance
GROUP BY category
HAVING COUNT(*) > 1;


-- Export

COPY gold_category_performance
TO '/mnt/c/Users/Lenovo/DataProjects/data-quality-pipeline/data/04-gold/gold_category_performance.parquet'
(FORMAT PARQUET);


-- Read-back verification

SELECT *
FROM read_parquet(
    '/mnt/c/Users/Lenovo/DataProjects/data-quality-pipeline/data/04-gold/gold_category_performance.parquet'
);


-- ============================================================================
-- 04. GOLD STORE PERFORMANCE
-- Business question:
-- Which stores generate the most net revenue and total margin?
--
-- Grain: one row per store with completed-order activity
-- ============================================================================

CREATE OR REPLACE TABLE gold_store_performance AS
SELECT
    sc.store_id,
    sc.name,

    COUNT(DISTINCT oc.order_no) AS completed_orders,

    SUM(oic.quantity) AS units_sold,

    ROUND(
        SUM(
            oic.quantity
            * oic.unit_price
            * (1 - oic.discount / 100)
        ),
        2
    ) AS net_revenue,

    ROUND(
        SUM(
            oic.quantity
            * (
                oic.unit_price * (1 - oic.discount / 100)
                - pc.unit_cost
            )
        ),
        2
    ) AS total_margin

FROM stores_clean AS sc
INNER JOIN orders_clean AS oc
    ON sc.store_id = oc.store_ref
INNER JOIN order_items_clean AS oic
    ON oc.order_no = oic.order_no
INNER JOIN products_clean AS pc
    ON pc.prod_code = oic.product_code
WHERE oc.status = 'completed'
  AND pc.active = 'Y'
GROUP BY
    sc.store_id,
    sc.name;


-- Validation

SELECT *
FROM gold_store_performance
ORDER BY total_margin DESC;

SELECT COUNT(*) AS row_count
FROM gold_store_performance;

SELECT COUNT(DISTINCT store_id) AS distinct_stores
FROM gold_store_performance;

SELECT
    store_id,
    COUNT(*) AS occurrences
FROM gold_store_performance
GROUP BY store_id
HAVING COUNT(*) > 1;


-- Export

COPY gold_store_performance
TO '/mnt/c/Users/Lenovo/DataProjects/data-quality-pipeline/data/04-gold/gold_store_performance.parquet'
(FORMAT PARQUET);


-- Read-back verification

SELECT *
FROM read_parquet(
    '/mnt/c/Users/Lenovo/DataProjects/data-quality-pipeline/data/04-gold/gold_store_performance.parquet'
);


-- ============================================================================
-- 05. GOLD CUSTOMER PERFORMANCE
-- Business question:
-- Which customers generate the most net revenue and total margin?
--
-- Grain: one row per customer with completed-order activity
-- ============================================================================

CREATE OR REPLACE TABLE gold_customer_performance AS
SELECT
    cc.customer_id,
    cc.full_name,

    COUNT(DISTINCT oc.order_no) AS completed_orders,

    SUM(oic.quantity) AS units_sold,

    ROUND(
        SUM(
            oic.quantity
            * oic.unit_price
            * (1 - oic.discount / 100)
        ),
        2
    ) AS net_revenue,

    ROUND(
        SUM(
            oic.quantity
            * (
                oic.unit_price * (1 - oic.discount / 100)
                - pc.unit_cost
            )
        ),
        2
    ) AS total_margin

FROM customers_clean AS cc
INNER JOIN orders_clean AS oc
    ON cc.customer_id = oc.cust_ref
INNER JOIN order_items_clean AS oic
    ON oc.order_no = oic.order_no
INNER JOIN products_clean AS pc
    ON oic.product_code = pc.prod_code
WHERE oc.status = 'completed'
  AND pc.active = 'Y'
GROUP BY
    cc.customer_id,
    cc.full_name;


-- Validation

SELECT *
FROM gold_customer_performance
ORDER BY total_margin DESC;

SELECT COUNT(*) AS row_count
FROM gold_customer_performance;

SELECT COUNT(DISTINCT customer_id) AS distinct_customers
FROM gold_customer_performance;

SELECT
    customer_id,
    COUNT(*) AS occurrences
FROM gold_customer_performance
GROUP BY customer_id
HAVING COUNT(*) > 1;


-- Export

COPY gold_customer_performance
TO '/mnt/c/Users/Lenovo/DataProjects/data-quality-pipeline/data/04-gold/gold_customer_performance.parquet'
(FORMAT PARQUET);


-- Read-back verification

SELECT *
FROM read_parquet(
    '/mnt/c/Users/Lenovo/DataProjects/data-quality-pipeline/data/04-gold/gold_customer_performance.parquet'
);

-- ============================================================================
-- END OF GOLD ANALYTICS
-- ============================================================================
